# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# Julia support: https://discourse.julialang.org/t/psa-github-dependabot-now-supports-julia/134997
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - ".buildkite"  # TODO: remove this if/when we move to [workspaces]
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups: # groups all julia package updates into a single PR
      all-julia-packages:
        patterns:
          - "*"
