name = "ClimaCore"
uuid = "d414da3d-4745-48bb-8d80-42e94e092884"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.13.3"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
CubedSphere = "7445602f-e544-4518-8976-18f8e8ae6cdb"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
GilbertCurves = "88fa7841-ef32-4516-bb70-c6ec135699d9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiBroadcastFusion = "c3c07f87-98de-43f2-a76f-835b330b2cbb"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"

[extensions]
KrylovExt = "Krylov"

[compat]
Adapt = "3, 4"
BandedMatrices = "0.17, 1"
BlockArrays = "0.16"
CUDA = "5"
ClimaComms = "0.5.7"
CubedSphere = "0.2"
DataStructures = "0.18"
DocStringExtensions = "0.8, 0.9"
ForwardDiff = "0.10"
GaussQuadrature = "0.5"
GilbertCurves = "0.1"
HDF5 = "0.16, 0.17"
InteractiveUtils = "1"
IntervalSets = "0.5, 0.6, 0.7"
Krylov = "0.9"
KrylovKit = "0.6"
LinearAlgebra = "1"
MultiBroadcastFusion = "0.2"
PkgVersion = "0.1, 0.2, 0.3"
RecursiveArrayTools = "2, 3"
RootSolvers = "0.3, 0.4"
SparseArrays = "1"
Static = "0.4, 0.5, 0.6, 0.7, 0.8"
StaticArrays = "1"
Statistics = "1"
Unrolled = "0.1"
julia = "1.9"
