name = "ClimaCore"
uuid = "d414da3d-4745-48bb-8d80-42e94e092884"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.14.49"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
ClimaInterpolations = "dd0f122e-fa3b-47f3-bcf0-93bbc60d885e"
CubedSphere = "7445602f-e544-4518-8976-18f8e8ae6cdb"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
GilbertCurves = "88fa7841-ef32-4516-bb70-c6ec135699d9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LazyBroadcast = "9dccce8e-a116-406d-9fcc-a88ed4f510c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultiBroadcastFusion = "c3c07f87-98de-43f2-a76f-835b330b2cbb"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnrolledUtilities = "0fe1646c-419e-43be-ac14-22321958931b"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"

[extensions]
ClimaCoreCUDAExt = "CUDA"
KrylovExt = "Krylov"

[compat]
Adapt = "3.2.0, 4"
Aqua = "0.8"
ArgParse = "1"
AssociatedLegendrePolynomials = "1"
BandedMatrices = "1"
BenchmarkTools = "1"
BlockArrays = "1"
CUDA = "5.5"
ClimaComms = "0.6.2"
ClimaInterpolations = "0.1.1"
CountFlops = "0.1"
CubedSphere = "0.2, 0.3"
DataStructures = "0.18.13, 0.19"
Dates = "1"
FastBroadcast = "0.3.1"
ForwardDiff = "0.10.15, 1"
GaussQuadrature = "0.5.8"
GilbertCurves = "0.1"
HDF5 = "0.16.16, 0.17"
InteractiveUtils = "1"
IntervalSets = "0.5, 0.6, 0.7"
JET = "0.9"
Krylov = "0.9, 0.10"
KrylovKit = "0.6, 0.7, 0.8"
LazyBroadcast = "1"
LinearAlgebra = "1"
Logging = "1"
MultiBroadcastFusion = "0.3.1, 0.4"
NVTX = "0.3, 1"
PkgVersion = "0.1, 0.2, 0.3"
PrettyTables = "2"
Random = "1"
RecursiveArrayTools = "3.2"
RootSolvers = "0.3, 0.4, 1.0"
SafeTestsets = "0.1"
SparseArrays = "1"
StaticArrays = "1.9.8"
Statistics = "1"
StatsBase = "0.34"
TerminalLoggers = "0.1"
Test = "1"
UnrolledUtilities = "0.1.9"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CountFlops = "1db9610d-79e1-487a-8d40-77f3295c7593"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LazyBroadcast = "9dccce8e-a116-406d-9fcc-a88ed4f510c8"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ArgParse", "AssociatedLegendrePolynomials", "BenchmarkTools", "CountFlops", "Dates", "FastBroadcast", "Krylov", "JET", "LazyBroadcast", "Logging", "PrettyTables", "Random", "SafeTestsets", "StatsBase", "TerminalLoggers", "Test"]
