name: ClimaCoreSpectra CI
on:
  pull_request:

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lib-climacore-spectra:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - uses: julia-actions/cache@v2
      - name: Install Julia dependencies
        run: >
          julia --project=monorepo -e 'using Pkg; Pkg.develop(path="$(pwd())"); Pkg.develop(path="$(pwd())/lib/ClimaCoreSpectra")'
      - name: Run the tests
        continue-on-error: true
        env:
            GKSwstype: nul
            CI_OUTPUT_DIR: output
        run: >
          julia --project=monorepo -e 'using Pkg; Pkg.test("ClimaCoreSpectra")'
          && echo "TESTS_SUCCESSFUL=true" >> $GITHUB_ENV
      - name: Upload test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: climacore-spectra-output
          path: |
            lib/ClimaCoreSpectra/test/output
      - name: Fail after artifacts if tests failed
        if: ${{ env.TESTS_SUCCESSFUL != 'true' }}
        run: exit 1
