name: Documentation

on:
  pull_request:

jobs:
  docbuild:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.9
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - name: Build and deploy
        env:
          GKSwstype: "100" # headless GR: https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988/2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
